version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install Dependencies"
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running Tests"
          npm run test
  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install Dependencies"
          npm install
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/my-node-app .
          # Change this to your Docker image name
      - run:
          name: Log into Docker Hub
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
           # Use Docker Token
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/my-node-app
          # Push to Docker Hub 

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push
