version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@1.4.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install Dependencies"
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running Tests"
          npm run test
  publish:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          name: Log into Docker Hub
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
           # Use Docker Token
      - docker/build:
          name: Build Docker Image
          image: $DOCKER_REGISTRY/my-node-app:latest
      - docker/push:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKER_REGISTRY/my-node-app:latest
          # Push to Docker Hub
      - run: |
          echo "Building image"

workflows:
  simple_workflow:
    jobs:
      - build
      # - test:
          # requires:
            # - build
      - publish:
          requires:
            - build
